### ISSUE TITLE
Header and Footer Styling Issues

### ISSUE THREAD

**Issue by kpmccaffrey** [NHSDigital/nhsuk-react-components#195]
Are there any examples repos of these components being used in github repos? 

I'm seeing styling issues when creating a simple React App. But I'm not too familliar with React so not sure if I'm missing something.

![image](https://github.com/NHSDigital/nhsuk-react-components/assets/34425905/83570f22-3a91-470b-8a20-0682a065d468)

**Comment by JoshuaBates-NHS** [comment]
Hi @kpmccaffrey 

This is due to the version of nhsuk-frontend you're using not being fully supported with the current version of nhsuk-react-components. We're working on realigning this as part of work done on `feature/nhsuk-frontend-v8`.

I'll feedback to this thread when changes are implemented and released

**Comment by jakeb-nhs** [comment]
This issue should now be fixed by the latest release https://github.com/NHSDigital/nhsuk-react-components/releases/tag/v4.0.0
