### ISSUE TITLE
Can't set the value of the `DateInput` component

### ISSUE THREAD

**Issue by kevinkuszyk** [NHSDigital/nhsuk-react-components#31]
Hello folks,

I have the latest (`1.2.3`) package installed and I'm trying to set the value on a `DateInput`:

```
render() {
    const value = {
        day: 1,
        month: 2,
        year: 2020
    }
    
    return (
        <DateInput value={value} />
    )
}
```

But it does not render:
 
<img width="282" alt="Screenshot 2020-06-10 at 09 47 00" src="https://user-images.githubusercontent.com/2734580/84247093-800dec80-aaff-11ea-8f7a-47387e13fc40.png">

It looks like the value is set, but not passed into the state:

<img width="303" alt="Screenshot 2020-06-10 at 09 47 24" src="https://user-images.githubusercontent.com/2734580/84247139-8e5c0880-aaff-11ea-83d0-023ef6e25b0e.png">

I'm a bit busy this week, but I'll try to get a PR in next week.

**Comment by lukepearson** [comment]
Hi @kevinkuszyk, 
I'm unable to replicate this bug see the sandbox:
https://codesandbox.io/s/nhsuk-react-component-test-l0usj?file=/src/App.tsx

The only thing I can see that isn't right is that day/month/year should be strings rather than numbers, but it compiles fine and works with numbers so that's probably irrelevant

Are you able to provide any more details, or post a link to some code which replicates the issue?

**Comment by kevinkuszyk** [comment]
@lukepearson @Tomdango thanks for your help on this.  

It turns out it was my bad - something went wrong on my machine when updating the package and having `yarn start` running at the same time.

Anyway, long story short is it is working as expected after all.
