### ISSUE TITLE
Requirement for controlling Alignment of Navigation Items

### ISSUE THREAD

**Issue by simonireilly** [NHSDigital/nhsuk-react-components#56]
I have a requirement to overwrite the `justify-content` properties of the CSS class set on the unordered list of the navigation items.

See:

https://github.com/NHSDigital/nhsuk-react-components/blob/6dd89396101e350aaa658d301b7fb1d714dd7b4b/src/components/header/components/Nav.tsx#L33

### Proposed Change

Since the `Header.Nav` component is closed for extension then I would think it could be refactored to:

1. Export a new component `Header.NavList` that allows structuring a `Header.Nav` from scratch.

This probably means that there must also be a `Header.NavContainer` and a `Header.NavTitle` to make the full implementation composable.

_Example_

```jsx
<Header.NavContainer>
    <Header.NavTitle title='menu'/>
    <Header.NavList
        className="nhsuk-u-justify-content-left"
    >
        <Header.NavItem>
            Something I want left aligned
        </Header.NavItem>
    </Header.NavList>
</Header.NavContainer>
```

This seems like a nice way to leave behind a trail of open components, and then perform dependency injection through `children` props whenever full customisation (open for extension) is needed. WDYT?

**Comment by Tomdango** [comment]
Hi Simon,

This looks good - I'm a fan of adding a separate implementation of `Header.Nav` rather than replacing it, as pretty much nearly every service currently using the package is using it. The only slight issue I have with the example is that I'd prefer `<Header.NavTitle>` to have it's content passed through as a child rather than a prop, but that might just be personal preference.

**Comment by Tomdango** [comment]
Closing this as https://github.com/NHSDigital/nhsuk-react-components/pull/57 has been merged.
